# Generated by Django 4.1.1 on 2022-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quinnemployee',
            name='nickname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
