# Generated by Django 4.1.1 on 2022-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_quinnemployee_active_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quinnemployee',
            name='original_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quinnemployee',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
