# Generated by Django 4.1.1 on 2022-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_quinnemployee_original_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_code', models.CharField(max_length=10)),
                ('function_code', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
